### ISSUE TITLE
go GET is getting "net/http: TLS handshake timeout" error

### ISSUE THREAD

**Issue by AnilChoudhury-Eaton** [alihanyalcin/meta-edgex#12]
Hi,
I am trying to build meta-edgex and I am getting following build issue. can you help me understand how to fix this?

| ERROR: Execution of '/home/anil/git/px-red-yocto/build/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/edgex-cli/1.0-r0/temp/run.do_compile.75583' failed with exit code 1:
| go: github.com/BurntSushi/toml@v0.3.1: Get "https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod": net/http: TLS handshake timeout
| go: github.com/BurntSushi/toml@v0.3.1: Get "https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod": net/http: TLS handshake timeout
| WARNING: /home/anil/git/px-red-yocto/build/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/edgex-cli/1.0-r0/temp/run.do_compile.75583:1 exit 1 from 'arm-poky-linux-gnueabi-go install -p 6 -v -ldflags="-r /usr/lib/go/pkg/linux_arm_dynlink  -extldflags ' -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a8 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/anil/git/px-red-yocto/build/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/edgex-cli/1.0-r0/recipe-sysroot -Wl,-rpath-link=/home/anil/git/px-red-yocto/build/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/edgex-cli/1.0-r0/recipe-sysroot/usr/lib/go/pkg/linux_arm_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now'" -modcacherw -buildmode=pie `go_list_packages`'
|
ERROR: Task (/home/anil/git/px-red-yocto/meta-pxred/meta-edgex/recipes-core/edgex-cli/edgex-cli.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4378 tasks of which 4373 didn't need to be rerun and 4 failed.

Summary: 4 tasks failed:
  /home/anil/git/px-red-yocto/meta-pxred/meta-edgex/recipes-core/edgex-core-contracts/edgex-core-contracts.bb:do_compile
  /home/anil/git/px-red-yocto/meta-pxred/meta-edgex/recipes-core/edgex-configuration/edgex-configuration.bb:do_compile
  /home/anil/git/px-red-yocto/meta-pxred/meta-edgex/recipes-support/go-redis/go-redis.bb:do_compile
  /home/anil/git/px-red-yocto/meta-pxred/meta-edgex/recipes-core/edgex-cli/edgex-cli.bb:do_compile
Summary: There were 4 ERROR messages shown, returning a non-zero exit code.

**Comment by alihanyalcin** [comment]
looks like cannot fetch the [toml](https://github.com/BurntSushi/toml) package to build go binary. 

can you try to clean the package using `bitbake –c clean <recipe>` and build again?
