### ISSUE TITLE
Integration to gatesgarth

### ISSUE THREAD

**Issue by Rohini8** [alihanyalcin/meta-edgex#13]
We are trying to integrate meta-edgex (master branch) to gatesgarth. Modified the following line in layer.conf
"LAYERSERIES_COMPAT_meta-edgex = "zeus dunfell gatesgarth"".
All the microservices are building except two services i.e core-data and export-distro. These two services are throwing the following error:

| ../../../../../recipe-sysroot-native/usr/lib/go/src/net/cgo_linux.go:10:10: fatal error: netdb.h: No such file or directory
|    10 | #include <netdb.h>
|       |          ^~~~~~~~~
| compilation terminated.
| Makefile:47: recipe for target 'cmd/export-distro/export-distro' failed
| make: *** [cmd/export-distro/export-distro] Error 2
| make: *** Waiting for unfinished jobs....
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/imx8qm_build/sources/meta-edgex-master/recipes-edgex/edgex/edgex_1.1.bb:do_compile) failed with exit code '1'

To solve the above error, we defined include and library paths in the makefile using CGO_CFLAGS and CGO_LDFLAGS as mentioned below:
CGO_CFLAGS=-I/build-xwayland/tmp/work/cortexa72-cortexa53-crypto-poky-linux/edgex/1.1-r1/recipe-sysroot/usr/include -O 
CGO_LDFLAGS=-L/build-xwayland/tmp/work/cortexa72-cortexa53-crypto-poky-linux/edgex/1.1-r1/recipe-sysroot/usr/lib -L/build-xwayland/tmp/work/cortexa72-cortexa53-crypto-poky-linux/edgex/1.1-r1/recipe-sysroot/usr/lib/aarch64-poky-linux/10.2.0/ -L/build-xwayland/tmp/work/cortexa72-cortexa53-crypto-poky-linux/edgex/1.1-r1/recipe-sysroot/lib

Getting the following error:

| /imx8qm_build/build-xwayland/tmp/work/cortexa72-cortexa53-crypto-poky-linux/edgex/1.1-r1/recipe-sysroot-native/usr/lib/go/pkg/tool/linux_amd64/link: running aarch64-poky-linux-gcc failed: exit status 1
|/imx8qm_build/build-xwayland/tmp/work/cortexa72-cortexa53-crypto-poky-linux/edgex/1.1-r1/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/ld: cannot find Scrt1.o: No such file or directory
|/imx8qm_build/build-xwayland/tmp/work/cortexa72-cortexa53-crypto-poky-linux/edgex/1.1-r1/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/ld: cannot find crti.o: No such file or directory
| /imx8qm_build/build-xwayland/tmp/work/cortexa72-cortexa53-crypto-poky-linux/edgex/1.1-r1/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/ld: cannot find crtbeginS.o: No such file or directory
| collect2: error: ld returned 1 exit status
 Makefile:50: recipe for target 'cmd/export-distro/export-distro' failed
| make: *** [cmd/export-distro/export-distro] Error 2
| WARNING: exit code 1 from a shell command.

We are facing these issues while building core-data and export-distro microservices. Please help us in fixing these errors and integrating meta-edgex layer to gatesgarth version.

**Comment by alihanyalcin** [comment]
hi, you can add glibc or libc6 as build dependencies.

**Comment by Rohini8** [comment]
hi,
We tried adding the following line in local.conf:
IMAGE_INSTALL_append  += "zeromq-dev libc6-dev libgcc-dev"

and also modified "DEPENDS" in edgex_1.1.bb as:
DEPENDS = "zeromq \
	glibc"
	
But still facing the same error.
